version: 2.0

jobs:
  test:
    docker:
      - image: ruby:2.6

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum "conflisp.gemspec" }}
            - v1-bundle-{{ .Branch }}-
            - v1-bundle-

      - run: bundle install

      - save_cache:
          key: v1-bundle-{{ .Branch }}-{{ checksum "conflisp.gemspec" }}
          paths:
            - ~/conflisp-ruby/vendor/bundle

      - run:
          name: Run tests
          command: |
            bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o tmp/junit.xml

      - run:
          name: Run linter
          command: |
            bundle exec rubocop

      # Store the coverage artifacts in case we want to review them
      - store_artifacts:
          path: coverage

      - store_test_results:
          path: tmp

      - run:
          name: Send Coverage to Codacy
          command: |
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report --coverage-reports coverage/lcov/project.lcov

  # Based on https://medium.com/@pezholio/publishing-rubygems-using-circle-ci-2-0-1dbf06ae9942
  deploy:
    docker:
      - image: ruby:2.6

    steps:
      - checkout

      - run:
          name: Setup Rubygems
          command: |
            mkdir ~/.gem
            echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials

      - deploy:
          name: Publish to Rubygems
          command: |
            gem build conflisp.gemspec
            gem push "conflisp-$(git describe --tags).gem"

workflows:
  version: 2
  continuous_integration:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - test
          context: rubygems
